bad specs
gitpetr/movie pull request #1
Opened 2017-04-11 11:47 UTC by gitpetr

2017-04-11 14:36 UTC, zverok requested changes
Начало положено! Дальше будет только интереснее.

2017-04-11 14:36 UTC, zverok commented on spec/movie_test.rb
> +MANTH = %i[Январь Февраль Март Апрель Май Июнь Июль Август Сентябрь Октябрь Ноябрь Декабрь]
зачем эти константы здесь?

2017-04-11 14:36 UTC, zverok commented on spec/movie_test.rb
> +  end
Так. Смотри. Чтобы получилась хорошая спека, мы думаем:
а) что именно (какое поведение) мы тестируем
б) какие для него предусловия и переменные нужны

Все значения создаются при помощи `let` или `subject` (это нужно, чтобы они пересоздавались на каждом запуске теста) — о них стоит почитать вот здесь: http://betterspecs.org/ (только в английской версии — русский перевод адски устарел), и тесты, в иделае, должны быть однострочными.

Чтобы отдизайнить тесты в целом, их можно попробовать описать для начала просто «текстом», вот так:

```ruby
describe MovieCollection do
  it 'загружается из файла' 
  it 'содержит все фильмы из файла'
  it 'позволяет отфильтровать фильмы' 
  ...и т.д.
end
```

Скорее всего, некоторые или все из этих `it` потом превратятся в `context` (объединение тестов, тестирующих одно и то же в разных условиях, например «когда один фильтр, когда много фильтров, когда неизвестный фильтр» и т.д.). Во многом у тебя это уже и сделано, в общем.

2017-04-11 14:36 UTC, zverok commented on spec/movie_test.rb
> +  end
Смотри, вот на примере этого — как имеет смысл писать такого рода тесты:

```ruby
describe '#stats' do # мы описываем поведение метода stats
  subject { listfilms.stats(field) } # предметом теста является результат stats

  context 'по режиссёрам' do # проверяем что работает для поля-немассива
    let(:field) { :director }
    it { is_expected.to include('Allen Woody' => 1, ....) } # it { is_expected ... — короткая форма, которую позволяет subject
  end

  context 'по актёрам' do # проверяем, что работает и для поля массива...

  context 'по незнакомому полю' do # проверим, какая будет ошибка
end
```

2017-04-17 10:43 UTC, zverok requested changes
Нормально, двигаемся дальше!

2017-04-17 10:43 UTC, zverok commented on modernmovie/modernmovie.rb
> +def create year
Этот метод кажется не используется же?

2017-04-17 10:43 UTC, zverok commented on classicmovie.rb
> +   end
Лучше этот метод назвать как-нибудь вроде `description`, и сделать однострочный вывод (чтобы удобно было списком печатать), в задании — _количество_ других фильмов этого режиссёра в топ (ну чтобы стало понятно насколько он крут), а не их список.

2017-04-17 10:43 UTC, zverok commented on modernmovie.rb
> +  end
Это не очень рубёвый способ собирать строки — тут бы нормально всё смотрелось и в одну строку:
```ruby
" #{ @name } - современное кино ( #{ @year }, - #{ @duratation }). Играют #{ @actors.join(', ') }."
```
Другой вариант — можно использовать метод format, чтобы аккуратнее было:
```ruby
format("%s - современное кино (%i - %i). Играют %s",
 @name,
 @year,
 @duration,
 @actors.join(', ')
)
```

2017-04-17 10:43 UTC, zverok commented on movie_collection.rb
> +    @allfilms = CSV.read(filmfile, col_sep: '|', headers: TITRES ).map{ |f| class_for(f.to_h[:year].to_i)\
тут без слеша в конце строчки можно обойтись, руби и так поймёт. Кстати, я бы отформатировал вот так, для пущей читабельности:
```ruby
CSV.read(filmfile, col_sep: '|', headers: TITRES )
  .map{ |f| class_for(f.to_h[:year].to_i).new(self, f.to_h) }
  .sort_by{|f| f.rating * rand(3) }.reverse
```
(так у нас весь `map` на одной строчке, и в целом читается последовательность хорошо: «прочитали файл → map → sort»)

2017-04-17 10:43 UTC, zverok commented on movie_collection.rb
> +    when (1900..1945) then
`then` не нужен и без него сработает. И скобки вокруг диапазона не нужны, будет аккуратнее:
```ruby
case year
when 1900..1945 # читается совершенно естественно
```

2017-04-17 10:43 UTC, zverok commented on netflix/netflix.rb
> +    {ancient: 1900..1945, classic: 1946..1968, modern: 1969..2000, new: 2001..Time.now.year}
Кажется, у нас тут происходит дублирование (в `class_for` та же информация записана чуть другими словами), а дублирование это всегда нехорошо (если мы вдруг решим поменять границы годов или добавить ещё один период, придётся править в нескольких местах).

2017-04-17 10:43 UTC, zverok commented on netflix/netflix.rb
> +    end
Лучше задать начальное значение в `initialize`, тогда можно будет обойтись без этого `if` (и другие методы не будут ломаться, например сейчас если попытаться что-то посмотреть, не заплатив, то условие `@deposit-cost` кинет ошибку «undefined method» вместо корректной «у вас недостаточно средств»)

2017-04-17 10:43 UTC, zverok commented on netflix/netflix.rb
> +  end
Логика должна быть такая:
1. находим фильмы по фильтрам
2. показываем один из них (случайным образом выбранный)
3. снимаем деньги со счёта за просмотр.

Как у настоящего онлайн-кинотеатра :)

2017-04-17 10:43 UTC, zverok commented on spec/netflix_spec.rb
> +TITRES = %i[link name  year country date  genre duratation rating director actors]
Зачем?

2017-04-17 10:43 UTC, zverok commented on spec/movie_spec.rb
> +    its(:year) { is_expected.to eq(1921) }
Это, вообще говоря, слабоватая проверка (а вдруг там только у первого фильма правильный год?). По-хорошему, надо бы проверить, что все фильмы отсортированы по годам :) Чтобы это сделать, у нас есть два варианта:

1) сделать свой матчер `be_sorted_by(field)` (это не сложно, на самом деле, несколько строчек кода), чтобы можно было написать
```ruby
subject { listfilms.sortby(:year) }
it { is_expected.to be_sorted_by(:year) }
```
...или матчер попроще, просто `be_sorted`:
```ruby
subject { listfilms.sortby(:year).map(&:year) }
it { is_expected.to be_sorted(:year) }
```

2) подготовить заранее (let) проверочный массив, и сделать что-то вроде:
```ruby
subject { listfilms.sortby(:year) }
it { is_expected.to eq movies_sorted_by_year }
```

Путь (1) конечно интереснее :)

2017-04-17 10:43 UTC, zverok commented on spec/netflix_spec.rb
> +  end
А другие методы?..

2017-04-17 10:43 UTC, zverok commented on theatre/theatre.rb
> +    elsif (19..24) === filters
Опять дублирование информации (константы `Morning`, `Day`, `Evening` и тут)

2017-04-17 10:43 UTC, zverok commented on theatre/theatre.rb
> +        puts "Сеансы фильма: #{f.film} идут #{Evening} "
Хорошо бы соответствие периода фильтам вынести в константу тоже, и тут её использовать.

2017-04-17 15:16 UTC, gitpetr commented on spec/netflix_spec.rb
> +TITRES = %i[link name  year country date  genre duratation rating director actors]
Ругается, что нет константы

2017-04-17 15:24 UTC, gitpetr commented on spec/netflix_spec.rb
> +  end
Надо по тестам отдельно побеседовать.
я не понимаю что подгружается, какие методы доступны, что нужно самому создавать.
Попытался, переменные не создаются, методы недоступны.
Я постоянно везде проверяю, что мне куда попадает, вот написал в одном классе p @collection, и забыл. Потом выводится класс и все. Я и так итак и так переписывал, и to_s переопределял в классе Netflix, перевод строки  все равно печатает. Хотел уже тебе писать. Закоммитил и сразу нашел откуда это идет.
  А в тестах не пойму откуда чего?

2017-04-17 15:26 UTC, gitpetr commented on spec/movie_spec.rb
> +    its(:year) { is_expected.to eq(1921) }
ощущение что я тупой

2017-04-18 11:03 UTC, zverok requested changes
На самом деле, общая форма уже вполне приличная. Несколько непониманий и недо-архитектуренных вещей мы разрулим!

2017-04-18 11:03 UTC, zverok commented on app/classicmovie.rb
> +   end
А ведь этот метод одинаковый у всех фильмов? Тогда его имеет смысл в Movie переместить

2017-04-18 11:03 UTC, zverok commented on app/movie_collection.rb
> +  def initialize filmfile,  firstpay=nil
А зачем этот параметр здесь? Он же этому классу не нужен, только дочерним классам? Значит, и добавлять его сюда смысла нету.

2017-04-18 11:03 UTC, zverok commented on app/netflix/netflix.rb
> +  def initialize filmfile, firstpay
Хорошо бы начальной сумме дефолтное значение параметра — 0, м? Чтобы в самом простом случае было проще работать с кинотеатром.

2017-04-18 11:03 UTC, zverok commented on app/theatre/theatre.rb
> +    end
В этом классе по-прежнему одна и та же информация (периоды — фильтры) дублируется и разбросана по коду. Вот это хорошо бы починить!

2017-04-18 11:03 UTC, zverok commented on spec/movie_spec.rb
> +TITRES = %i[link name  year country date  genre duratation rating director actors]
Надо разобраться, почему без этой строчки не работает. Ведь нигде в этом файле она не используется. Зачем она нужна, откуда прилетает ошибка если её убрать?

2017-04-18 11:03 UTC, zverok commented on spec/movie_spec.rb
> +    its(:year) { is_expected.to eq(1921) }
И совершенно напрасно. Просто очень уж много новой информации сразу.

2017-04-18 11:03 UTC, zverok commented on spec/netflix_spec.rb
> +  end
Давай побеседуем, да, в чятике.

2017-04-18 22:16 UTC, zverok commented on app/netflix/netflix.rb
> +    filter(filters).sort_by { rand }.first(1).each{|f| puts " Фильм: #{ f.description } #{ f.watch } " }
Тут кстати они получатся совсем случайные, а есть же ещё усложнение что «с большей вероятностью — больший рейтинг» ;) Ну так, на будущее.

2017-04-18 22:16 UTC, zverok commented on app/theatre/theatre.rb
> +  end
Чисто логически, тут должно быть чото такое:
* константа «когда какой фильтр»
* константа «когда какой период»
* метод `show` берёт текущее время, понимает (по константам) какой сейчас период, понимает (по константам) какой фильтр применить, фильтрует, показывает
* метод `when?` берёт имя фильма, проверяет (по константам) в какой период этот фильм входит, говорит (по константам) с какого по какой час он отображается.

Тогда логика методов будет железобетонная, и при смене требований надо будет менять только константы.

2017-04-18 22:16 UTC, zverok commented on spec/netflix_spec.rb
> +require_relative '../app/newmovie'
Вообще (к этому и всем остальным файлам):
* require всех нужных библиотек лучше в spec/spec_helper.rb положить
* наша библиотека про фильмы должна подключаться одной строчкой типа `require '../app/movies'` — а сама уже должна в нужной очерёдности свои файлы подгружать.

2017-04-19 02:02 UTC, gitpetr commented on app/netflix/netflix.rb
> +    filter(filters).sort_by { rand }.first(1).each{|f| puts " Фильм: #{ f.description } #{ f.watch } " }
```ruby
@allfilms = CSV.read(filmfile, col_sep: '|', headers: Movie::TITRES )
      .map{ |f| class_for(f.to_h[:year].to_i).new(self, f.to_h) }
      .sort_by{|f| f.rating * rand(3) }.reverse
```
здесь сортируется с большей вероятностью больший рейтинг
я проверял
```
[1,2,3,4,5,6,7,8,9].sort_by{rand(3)}.reverse
[8, 9, 7, 6, 5, 3, 2, 1, 4]
[8, 6, 2, 1, 7, 3, 9, 5, 4]
[3, 1, 8, 6, 4, 9, 7, 5, 2]
[8, 7, 6, 5, 4, 3, 1, 9, 2]
[6, 5, 3, 1, 8, 4, 9, 7, 2]
[4, 9, 8, 7, 3, 6, 5, 2, 1]
[9, 5, 3, 1, 8, 7, 6, 4, 2]
[5, 4, 3, 2, 8, 1, 9, 7, 6]
[9, 8, 5, 4, 2, 7, 6, 3, 1]
[4, 9, 5, 3, 2, 1, 8, 7, 6]
[8, 7, 6, 2, 1, 9, 5, 4, 3]
[9, 5, 6, 4, 2, 1, 8, 7, 3]
[8, 6, 4, 9, 7, 5, 2, 1, 3]
[8, 7, 6, 4, 3, 2, 9, 5, 1]
[4, 7, 6, 5, 9, 8, 3, 2, 1]

2017-04-19 02:54 UTC, gitpetr commented on app/netflix/netflix.rb
> +    filter(filters).sort_by { rand }.first(1).each{|f| puts " Фильм: #{ f.description } #{ f.watch } " }
сделал так 
```ruby
filter(filters).sort_by{ |f|  f.rating.to_i * rand(10) }.reverse.first(1).each{|f| puts " Фильм: #{ f.description } #{ f.watch } " }
```
Какую цифру в rand положить не знаю,
тут надо рассчитывать по теории вероятности, маленькая цифра, то с низким рейтингом фильм никогда не выберется, большая - выбор будет вообще в случайном порядке

2017-04-19 02:57 UTC, gitpetr commented on app/netflix/netflix.rb
> +    filter(filters).sort_by { rand }.first(1).each{|f| puts " Фильм: #{ f.description } #{ f.watch } " }
я находил алгоритм сортировки по рейтингу, чтото слишком сложный для меня был
Это я сам придумал. Работает же

2017-04-19 05:06 UTC, gitpetr commented on spec/netflix_spec.rb
> +require_relative '../app/newmovie'
Что ты все стесняешься подробно написать?
Пиши,  я не обижусь, а с удовольствием почитаю

2017-04-19 05:17 UTC, gitpetr commented on app/theatre/theatre.rb
> +  # FilterMorning = { year: @period[:ancient] }
Не получилось создать Константу FilterMorning
Говорит: period - нет такого метода, а в переменной @period - nil

2017-04-19 09:13 UTC, zverok commented on app/theatre/theatre.rb
> +  # FilterMorning = { year: @period[:ancient] }
Ну да, на этот момент никакого `@period` у нас нету. Можно же здесь въявную просто сделать фильтр `period: :ancient` и всё, не?

2017-04-19 09:32 UTC, gitpetr commented on app/theatre/theatre.rb
> +  # FilterMorning = { year: @period[:ancient] }
я в родительском классе инициализировал переменную @period,
почему ее здесь нет?

2017-04-19 15:13 UTC, zverok commented on app/theatre/theatre.rb
> +      filter(FILTRES[TIMES.map{ |k, v| k if  v === filters }.compact[0]]).each{ |f| f.description }
Вполне норм, только в данном случае не обязательно упаковывать всё в одну строчку, читабельнее будет. Плюс именуем все переменные понятным образом:
```ruby
def show(hour)
#....
period = TIMES.detect{ |p, hours| hours.cover?(hour) } # detect вместо map + compact[0] лучше выражает смысл
                                                       # а обобщённый === тут низачем, мы точно знаем что hours — это Range
filter(FILTRES[period])

2017-04-19 16:01 UTC, gitpetr commented on app/theatre/theatre.rb
> +      filter(FILTRES[TIMES.map{ |k, v| k if  v === filters }.compact[0]]).each{ |f| f.description }
я подозревал, что detect существует

2017-04-19 16:47 UTC, zverok commented on app/theatre/theatre.rb
>      end
Я бы сказал что `(9..24)`, вписанное в код прямо числами, нехорошо. Если такой период не найден — то достаточно сказать `if !period ... raise SomeError`. Тогда даже если наш кинотеатр сменит рабочие периоды, код не поломается.

2017-04-19 16:47 UTC, zverok commented on app/theatre/theatre.rb
>      end
Остальное кажется уже вполне осмысленно!

2017-04-24 06:09 UTC, merged