Композиция, попытка 2
gitpetr/movie pull request #3
Opened 2017-04-26 08:26 UTC by gitpetr

2017-04-26 15:43 UTC, zverok commented on app/cashbox.rb
> +      @cash += add
Вот тут можно сделать просто `@cash = cash + add` (тогда `||=` будет только в одном методе)

2017-04-26 16:14 UTC, gitpetr commented on app/cashbox.rb
> +      @cash += add
сделал

2017-04-26 20:49 UTC, zverok reviewed
Причеши всё и сделай общий модуль для всех своих классов (его можно продолжать в разных файлах), и пойдём дальше

2017-04-26 20:49 UTC, zverok commented on app/theatre/theatre.rb
> +    @cash = 0
это ж теперь не нужно.

2017-04-26 20:49 UTC, zverok commented on app/theatre/theatre.rb
> +  attr_accessor :cash
и это не нужно

2017-04-27 00:45 UTC, gitpetr commented on app/theatre/theatre.rb
> +  attr_accessor :cash
Я не знаю как можно сделать модуль из разных файлов, я бы уже сделал.
Не нашел как это делается

2017-04-27 10:23 UTC, zverok requested changes
Одна важная ошибка, плюс тестов бы для нового функционала, а?

2017-04-27 10:23 UTC, zverok commented on app/netflix/netflix.rb
> +      raise "Извините! У вас недостаточно средств на счете" unless  (self.class.cash - cost) >= 0
Не, смотри, тут хитрость в том, что на Netflix у нас есть два счёта:
* «пользовательский» как раньше (принадлежащий объекту, и показывающий сколько фильмов может создатель объекта посмотреть)
* и новая «касса» (принадлежащая всему классу и показывающая сколько мы заработали на всех юзерах)

2017-04-27 20:36 UTC, zverok requested changes
Ну и славно. Осталось добавить по одному маленькому тесту в Theatre и Netflix, убедиться что у первого касса раздельная (тест — добавляем денег двум разным кинотеатрам, они у них разные), а у второго общая (тест — добавляем денег двум разным нетфликсам, изменилась сумма в кассе класса).

2017-04-27 20:36 UTC, zverok commented on spec/cashbox_spec.rb
> +  end
В принципе, и так норм, но во всех методах, где мы тестируем «когда вызван этот метод, то-то должно измениться», красивше так:
```ruby
expect { netflix.take('Bank') }.to change(netflix, :cash).to(0)
# или, напр.,
expect{ netflix.addtocash 10}.to change(netflix, :cash).by(20)
```

2017-04-28 01:34 UTC, gitpetr commented on spec/cashbox_spec.rb
> +  end
Я только начинаю понимать как по простому.
Но ты мне пиши как красивше.
Когда по разному написано, то лучше понимается

2017-04-28 11:24 UTC, zverok approved these changes

2017-04-28 12:20 UTC, merged