check old cod
gitpetr/movie pull request #4
Opened 2017-05-10 10:43 UTC by gitpetr

2017-05-10 11:26 UTC, zverok commented on app/movie.rb
> +на счете осталось #{Money.new( 100 * @collection.deposit, "USD")}#{currency.symbol}"
Тяжело читать. Лучше так:
```ruby
    "Оплата просмотра фильма #{Money.new( 100 * self.cost, "USD")}#{currency.symbol}, "\
    "на счете осталось #{Money.new( 100 * @collection.deposit, "USD")}#{currency.symbol}"
```

(обрати внимание на кавычки в конце первой и начале второй строки)

2017-05-10 11:28 UTC, zverok commented on app/movie_collection.rb
> +      "\t#{k.to_s.ljust(15)} #{v}"
Теперь получается что метод называется `print_...`, но ничего не печатает :)

2017-05-10 11:31 UTC, zverok commented on .rubocop.yml
> +Rails:
Это тебе не нужно, с Rails мы тут не работаем :)

2017-05-10 11:31 UTC, zverok commented on .rubocop.yml
> +  Exclude:
Это тебе тоже не нужно :)

2017-05-10 12:57 UTC, gitpetr commented on app/movie.rb
> +на счете осталось #{Money.new( 100 * @collection.deposit, "USD")}#{currency.symbol}"
Ага, хотел спросить здесь

2017-05-10 12:58 UTC, gitpetr commented on app/movie_collection.rb
> +      "\t#{k.to_s.ljust(15)} #{v}"
Сразу не удаляю

2017-05-10 12:59 UTC, gitpetr commented on .rubocop.yml
> +Rails:
А будем?

2017-05-10 13:33 UTC, zverok commented on .rubocop.yml
> +Rails:
Со мной — неа. Но на mkdev есть другие менторы, они и рельсами занимаются.

2017-05-12 12:26 UTC, zverok requested changes

2017-05-12 12:26 UTC, zverok commented on .rubocop.yml
> +  Enabled: false
Это кстати полезный коп :) Ща закончу осмотр и в чятике объясню.

2017-05-12 12:26 UTC, zverok commented on spec/netflix_spec.rb
> +    it "when netflix.show(genre: /Sci-Fi|Comedy|Romance|Drama/, period: :modern)[0]" do
Тут перестаёт быть понятно, что ты описываешь. Раньше было лучше :(

2017-05-12 12:26 UTC, zverok commented on spec/netflix_spec.rb
> +    end
И где у нас тест на новый вариант `show`, с блоком?

2017-05-14 02:01 UTC, merged